### ISSUE TITLE
TypeError: Cannot read property 'undefined' of undefined

### ISSUE THREAD

**Issue by jamesyoung** [maticnetwork/sol-trace#1]
Instead of getting the line number of the revert in the smart contract, I am getting the following type error :

```
TypeError: Cannot read property 'undefined' of undefined
      at node_modules/sol-trace/build/source-maps.js:119:22
      at Array.forEach (<anonymous>)
      at parseSourceMap (node_modules/sol-trace/build/source-maps.js:94:11)
      at Web3TraceProvider._callee2$ (node_modules/sol-trace/build/web3-trace-provider.js:235:66)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by jdkanani** [comment]
This gets fixed by running `truffle compile` as `sol-trace` needs `build/contracts` folder and artifacts and following commit -

Rejecting empty bytecode (for interface) - https://github.com/maticnetwork/sol-trace/blob/master/src/web3-trace-provider.js#L238-L243


New problem -

It always generates same error message for spankbank.sol https://github.com/SpankChain/spankbank/blob/master/contracts/SpankBank.sol

```
Stack trace for REVERT:
/Users/<username>/spankbank/contracts/Token.sol:7:0
```

**Comment by jdkanani** [comment]
@federicobond any help would be appreciated :)
